spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/laroka
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          "time_zone": UTC
    show-sql: true

logging:
  structured:
    format:
      console:

jwt:
  secret: iUzEn+6BnkaXe2PVLxIZ2W0YTJ9AftQCcG5JxLLYLZ7IlCXffT69nnIEQXIIiJao
  expiration: 28800000
