name: CD Client

on:
  push:
    branches:
      - tp-devops
    paths:
      - 'client/**'

jobs:
  deploy:
    name: Deploy to Vercel (PWA)
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Vercel Deploy
        env:
          deploy_url: ${{ secrets.VERCEL_DEPLOY_HOOK_CLIENT }}
        run: curl -X POST "$deploy_url"